server:
  port: 9001
spring:
  application:
    name: cloud-client
  cloud:
    nacos:
      discovery:
        server-addr: www.cjlly.com:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

service-url:
  nacos-user-service: http://cloud-service


management:
  endpoints:
    web:
      exposure:
        include: "*"